apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata: 
      name: ui
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: cr.yandex/crp3i0t6u7tu1ddq94n8/ui:a01c268d
        ports:
          - containerPort: 8000
        env:
        - name: MONGO
          value: 
        - name: MONGO_PORT
          value: "27017"
